name: Docker tests
run-name: ${{ github.actor }} is running the test schedules.
on:
  push:
    branches:
      - GH_actions_test

jobs:
  run-scripts:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        pgver: [14, 15, 16, 17]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout snowflake
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Define Dockerfile name
        id: set-dockerfile
        run: |
          # Dynamically set the Dockerfile name based on the matrix version
          DOCKERFILE_NAME="Dockerfile${{ matrix.pgver }}"
          echo "DOCKERFILE_NAME=$DOCKERFILE_NAME" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t my-app:${{ matrix.pgver }} -f $DOCKERFILE_NAME .
        sleep 5

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt install -y postgresql-client \
            libpq-dev \
            python3-dev \
            python3-psycopg2 \
            python3-dotenv

    - name: Run Test Harness (runner.py)
      run: |
        python test/runner.py -c test/t/lib/${{ matrix.pgver }}config.env -s test/schedule_files/script_file -k
        cat latest.log

    - name: Upload Log File as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: latest-log-${{ matrix.pgver }}
        path: latest.log
