name: Test PostgreSQL Matrix
run-name: ${{ github.actor }} is running the test schedules.
on:
  push:
    branches:
      - GH_actions_test

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout snowflake
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker Image
      run: |
        docker build --progress plain -t snowflake .

    - name: Run Docker Container
      run: |
        docker run -d --name snowflake-container -e POSTGRES_PASSWORD=password -p 5432:5432 snowflake-test
        sleep 5

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt -y update
        sudo apt install -y postgresql-client-${{ matrix.pgver }} \
            libpq-dev \
            python3-dev \
            python3-psycopg2 \
            python3-dotenv

    - name: Run Test Harness (runner.py)
      run: |
        python test/runner.py -c test/t/lib/${{ matrix.pgver }}config.env -s test/schedule_files/script_file -k
